import type { Metadata } from "next";
// 1. تصحيح الاستيراد وإضافة Geist_Mono
import { IBM_Plex_Sans_Arabic, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AuthModalProvider } from "@/components/providers/auth-modal-provider";

// 2. إعداد الخط العربي بشكل صحيح
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-arabic",
  subsets: ["arabic", "latin"], // مهم جداً لدعم الحروف العربية
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

// 3. إعداد خط المونو (للأكواد)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // يفضل تغيير اللغة إلى ar واتجاه النص إذا كان الموقع عربي
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${ibmPlexSansArabic.variable} ${geistMono.variable} font-sans antialiased`}
      ><AuthModalProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </AuthModalProvider>
        <Analytics />
        <Toaster />
      </body>
    </html>
  );
}
